import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ReportData {
    name: string;
    type: string;
    description: string;
    data: any;
    createdAt: Date;
    tags: string[];
}

export const generateReportPDF = (report: ReportData): jsPDF => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // Header
    doc.setFontSize(20);
    doc.setTextColor(40, 40, 40);
    doc.text(report.name, 20, 20);

    // Metadata
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 30);
    doc.text(`Type: ${report.type.toUpperCase()}`, 20, 35);

    // Description
    if (report.description) {
        doc.setFontSize(11);
        doc.setTextColor(60, 60, 60);
        const descLines = doc.splitTextToSize(report.description, pageWidth - 40);
        doc.text(descLines, 20, 45);
    }

    let yPosition = report.description ? 55 + (doc.splitTextToSize(report.description, pageWidth - 40).length * 5) : 45;

    // Line separator
    doc.setDrawColor(200, 200, 200);
    doc.line(20, yPosition, pageWidth - 20, yPosition);
    yPosition += 10;

    // Report Content based on type
    doc.setFontSize(14);
    doc.setTextColor(40, 40, 40);
    doc.text('Report Summary', 20, yPosition);
    yPosition += 10;

    // Handle different data structures
    if (report.data) {
        doc.setFontSize(10);
        doc.setTextColor(60, 60, 60);

        if (report.data.insights && Array.isArray(report.data.insights)) {
            // AI Report format
            doc.text('Key Insights:', 20, yPosition);
            yPosition += 7;

            report.data.insights.forEach((insight: string, index: number) => {
                const lines = doc.splitTextToSize(`${index + 1}. ${insight}`, pageWidth - 40);
                doc.text(lines, 25, yPosition);
                yPosition += lines.length * 5 + 2;
            });

            if (report.data.recommendations) {
                yPosition += 5;
                doc.text('Recommendations:', 20, yPosition);
                yPosition += 7;

                report.data.recommendations.forEach((rec: string, index: number) => {
                    const lines = doc.splitTextToSize(`${index + 1}. ${rec}`, pageWidth - 40);
                    doc.text(lines, 25, yPosition);
                    yPosition += lines.length * 5 + 2;
                });
            }
        } else {
            // Generic data format - create table
            const dataEntries = Object.entries(report.data);

            if (dataEntries.length > 0) {
                const tableData = dataEntries.map(([key, value]) => [
                    key.replace(/([A-Z])/g, ' $1').trim(),
                    typeof value === 'object' ? JSON.stringify(value) : String(value)
                ]);

                autoTable(doc, {
                    startY: yPosition,
                    head: [['Metric', 'Value']],
                    body: tableData,
                    theme: 'striped',
                    headStyles: { fillColor: [255, 193, 7] },
                    margin: { left: 20, right: 20 }
                });

                yPosition = (doc as any).lastAutoTable.finalY + 10;
            }
        }
    }

    // Tags
    if (report.tags && report.tags.length > 0) {
        if (yPosition > pageHeight - 30) {
            doc.addPage();
            yPosition = 20;
        }

        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(`Tags: ${report.tags.join(', ')}`, 20, yPosition);
    }

    // Footer
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(
            `Page ${i} of ${totalPages}`,
            pageWidth / 2,
            pageHeight - 10,
            { align: 'center' }
        );
        doc.text(
            'Generated by Sartthi Project Management',
            pageWidth - 20,
            pageHeight - 10,
            { align: 'right' }
        );
    }

    return doc;
};

export const downloadReportPDF = (report: ReportData) => {
    const doc = generateReportPDF(report);
    const filename = `${report.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${new Date().getTime()}.pdf`;
    doc.save(filename);
};

export const printReportPDF = (report: ReportData) => {
    const doc = generateReportPDF(report);
    doc.autoPrint();
    window.open(doc.output('bloburl'), '_blank');
};
